---
# Note: OpenShift repositories under CentOS may be shipped through the
# "centos-release-openshift-origin" package which configures the repository.
# This task matches the file names provided by the package so that they are
# not installed twice in different files and remains idempotent.

- name: Configure origin gpg keys
  copy:
    src: "origin/gpg_keys/openshift-ansible-CentOS-SIG-PaaS"
    dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-PaaS"
  notify: refresh cache

# The version is hardcoded since we cannot use the openshift_version role
# (it uses the installed packages to determine the version).
- name: Configure correct origin release repository
  template:
    src: "CentOS-OpenShift-Origin310.repo.j2"
    dest: "/etc/yum.repos.d/CentOS-OpenShift-Origin310.repo"
  notify: refresh cache

# In some cases, the "latest" repository was used instead of the release repo
# due to https://github.com/openshift/openshift-ansible/issues/10445.
# Remove the repository to prevent issues when upgrading, now that we deploy
# the correct one.
- name: Remove CentOS-OpenShift-Origin.repo
  file:
    state: absent
    path: "/etc/yum.repos.d/CentOS-OpenShift-Origin.repo"

